version: '3.8'

services:
  invoice-app-staging:
    build:
      context: ..
      dockerfile: docker/Dockerfile.staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_ENV=staging
    env_file:
      - ../.env.staging
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoice-staging.rule=Host(`staging.yourcompany.com`)"
      - "traefik.http.routers.invoice-staging.tls=true"
      - "traefik.http.routers.invoice-staging.tls.certresolver=letsencrypt"

  # Optional: Database for staging
  postgres-staging:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: invoice_staging
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: staging_password
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_staging_data: